### ISSUE TITLE
何をするか考える

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2015-semi#1]
締切り 10/28 まで

**Comment by k-okada** [comment]
歩行させたい

```
sudo apt-get install ros-indigo-hrpsys
sudo apt-get install ros-indigo-rtmros-common
roslaunch hrpsys samplerobot.launch
rosrun hrpsys samplerobot_walk.py
```

http://wiki.ros.org/rtmros_common/Tutorials/GettingStart

**Comment by k-okada** [comment]
制御を勉強する環境が作れる
http://gazebosim.org/tutorials?tut=ros_urdf&ver=1.9%2B&cat=connect_ros

**Comment by k-okada** [comment]
fetch simulation http://docs.fetchrobotics.com/gazebo.html
http://ros-logger.blogspot.jp/2015/07/playing-with-fetch-and-freight-robots.html

**Comment by k-okada** [comment]
gazebo で飛行ロボットのシミュレーションをする
http://gazebosim.org/tutorials?tut=aerodynamics&cat=physics
https://www.dronecode.org/about

**Comment by k-okada** [comment]
Baxter Simulation https://github.com/RethinkRobotics/baxter_simulator

**Comment by k-okada** [comment]
Gazebo + Nao : https://github.com/ros-naoqi/nao_virtual

**Comment by knorth55** [comment]
gazeboで飛行ドローンARdroneのシミュレーションをする方法をみつけました
https://github.com/AutonomyLab/ardrone_autonomy
https://github.com/dougvk/tum_simulator
ardrone_autonomyとtum_simulatorをつかうことで動かすことができそうです。

**Comment by ban-masa** [comment]
gazeboでnaoのシミュレーションを表示することまでできました。
https://github.com/ros-naoqi/nao_virtual/blob/master/nao_gazebo_plugin/README.rst
コントロールする方法を理解するため調べているところです。
