### ISSUE TITLE
Point Cloudを用いたい

### ISSUE THREAD

**Issue by knorth55** [start-jsk/2015-semi#12]

**Comment by knorth55** [comment]
Point CloudやHeight Mapを用いて物体認識を試してみたいと思っています。
PCLのDocumentatioとjsk-recognitionのDocumentationを読んでいます。
Point CloudとHeight Mapの関係についてまだ理解できておらず学んでいます。

**Comment by knorth55** [comment]
[FPFH](http://pointclouds.org/documentation/tutorials/fpfh_estimation.php) について理解がまだ出来ていません。

**Comment by k-okada** [comment]
ask @wkentaro or @aginika, may be better to talk to him directory.

## 

◉ Kei Okada

**Comment by knorth55** [comment]
Point CloudをHeight Mapに変換して表示してみました。次回のゼミまでに何ができそうか調べてきます。
![screenshot from 2015-11-10 12 50 17](https://cloud.githubusercontent.com/assets/9300063/11053997/b9f9a7d2-87a9-11e5-9800-33bd77e17615.png)
