### ISSUE TITLE
End-to-End Training of Deep Visuomotor Policies 

### ISSUE THREAD

**Issue by kimhc6028** [start-jsk/2015-semi#42]
@knorth55 
maybe you want to do this...
Anyone else to participate?
https://www.youtube.com/watch?v=Q4bMcUk6pcw

**Comment by kimhc6028** [comment]
https://research.preferred.jp/2015/12/robot_binpick_deep_learning/

http://amazonpickingchallenge.org/

**Comment by knorth55** [comment]
yes !

**Comment by knorth55** [comment]
we can use this for [apc2016](https://github.com/start-jsk/jsk_apc/issues/1011#issuecomment-173861401)

**Comment by kimhc6028** [comment]
Nice Idea. Using deep learning for image recognition would make our job much easier..
