### ISSUE TITLE
2016 apc

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2015-semi#44]
ルールはこちら
http://archives.simplelists.com/pickingchallenge2016/cache/3300513/2.pdf

| PHASES | Event | Starts 12:00AM (ET) | Ends  11:59PM(ET) |
| --- | --- | --- | --- |
| PHASE 2: | Robot Proposal Review Period | February 1, 2016 | February 24, 2016 |
| PHASE 3: | Finalist Notification Period | February 25,2016 | February 26, 2016 |
| PHASE 4: | Finalist Event | June 29, 2016 | July 3, 2016 |
| PHASE 5: | Event Scoring | June 30, 2016 | July 3, 2016 |
|  | PRIZE WINNERS ANNOUNCED | July 3, 2016 |  |
- PHASE 1 “Robot Proposal Entry Period”: Entrant or Entrant Teams who wish to enter the Challenge
  may visit http://amazonpickingchallenge.org/ (“Challenge Site”) and submit the entry information
  required including, but not limited to: Entrant name, email address, team size, mailing address, daytime
  phone number, confirmation of age, and include an overview of their Robot in the form provided
  (collectively, a “Proposal Entry”).
- PHASE 2 “Robot Proposal Review Period”: All eligible Proposal Entries will be judged and scored by
  a review panel chosen by the Sponsor (“Review Panel”). The Review Panel will rank Proposal Entries
  based on the maturity and flexibility of the proposed design and the likelihood the design will result in
  successful performance in the Finalist Event (the “Review Criteria”). The Sponsor reserves the right to
  assess Proposal Entries in the manner determined by the Sponsor, which may include interviews or
  discussions with certain Entrants/Entrant Teams.
  The sixteen (16) Proposal Entries ranked highest by the Review Panel will be deemed potential inalists
  (subject to verification and compliance with these Official Rules) and will be invited to attend RoboCup
  2016 scheduled to take place in Leipzig, Germany from June 30 to July 4, 2016 where they will have the opportunity to have their Robot compete against other finalist Robots (the “Finalist Event”). In the event of a tie, all tied Proposal Entries will be re-reviewed by an additional “tie-breaking” panel member selected by Sponsor who will use the Review Criteria above to break the tie. Sponsor’s decisions are final and binding in all matters relating to this Challenge.
- PHASE 3 “Finalist Notification Period”: Potential finalists are subject to verification by the Challenge
  Entities. Potential finalists will be notified by email at the email address provided at time of Proposal
  Entry. Potential finalists (and if an Entrant Team, all members of such team) will be required to complete and return a Participation Agreement, within the timeframe stated on the notification. If any email notification is returned as undeliverable, if a potential finalist does not respond within the required number of days specified by Sponsor, or if information collected within the clearance documentation, entry, or background check is found in non-compliance with these Official Rules, raises other issues of significant concern to Sponsor or a potential winner decides to decline the prize for any reason whatsoever, Sponsor shall have no further obligation to such potential finalist and the applicable prize will be forfeited and may be awarded to a runner-up potential finalist time-permitting and at the Sponsor’s sole discretion. 
- PHASE 4 “Finalist Event”:
  Overview
  The Finalist Event will consist of two tasks:
  • A pick task to remove target items from a shelf and place them in a tote, and
  • A stow task to take target items from a tote and place them into the shelf.

**Comment by k-okada** [comment]
箱から物を棚に戻すタスクが増えたのかな？
ロボットは借りられるんだろうか？

**Comment by pazeshun** [comment]
最後の行はそんなこと言ってる気がしますね。
2月に書類選考的何かがあるとは知らなかったです。
まずはそこを突破しないといけないってことですかね

**Comment by kimhc6028** [comment]
試験終わったらすぐ始まりたいと思います。
phase 2のためにはすぐ始まらなければいけないですかね。。

**Comment by kimhc6028** [comment]
@k-okada 
岡田先生、私と長谷川は、apcの打ち合わせをしないとやりとりが進まないかなと思って、研究室で一回ぐらい集まった方がいいと思いますが、いつが良いでしょうか？

**Comment by k-okada** [comment]
いつでもいいです
今日は16:00以降
明日は午前か15:00ー19:00
明後日は15:00以降
が空いています

## 

◉ Kei Okada

2016/01/20 13:10、Kim Heecheol notifications@github.com のメッセージ:

**Comment by knorth55** [comment]
話し合いに参加したいです！

**Comment by kimhc6028** [comment]
岡田先生
明日(22日)の15時に行きたいと思います。ゼミの人全員参加します。よろしくお願いします

**Comment by k-okada** [comment]
http://amazonpickingchallenge.org/APC_2016_Official_Rules.pdf
