### ISSUE TITLE
PCについて

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/2015-semi#45]
@k-okada 先生
今週、空いているお時間はありますでしょうか。
もう2台PCをお借りしたいのと、OSの新規インストールが必要か必要じゃないかなどについて落ち着いて話したいです。

**Comment by k-okada** [comment]
はい．あしたの12:30-15:00 以外はだいたいいます．

## 

◉ Kei Okada

2016-01-27 23:18 GMT+09:00 pazeshun notifications@github.com:

**Comment by pazeshun** [comment]
あと、現時点でお貸しいただいてるPCのうち、msiの方を @kimhc6028 が持って帰りました。
あのPCはすでにUbuntuが入っていると思いますが、そのまま使ってしまってもよいのでしょうか。それとも、お借りした白USBなどを使ってUbuntuを入れなおすべきなのでしょうか

**Comment by pazeshun** [comment]
了解しました。
@knorth55 が明日伺うみたいなので、一台お貸しいただければと思います。

**Comment by pazeshun** [comment]
僕は、明後日研究室に行こうと思っているので、僕と @ban-masa の分はそこで相談させてください。

**Comment by k-okada** [comment]
Msiそのまま使ってＯＫです
再インストールしていいかは @furushchev に聞いてみて下さい

## 

◉ Kei Okada

2016/01/27 23:21、pazeshun notifications@github.com のメッセージ:

**Comment by furushchev** [comment]
再インストールしても大丈夫と思います。
注意点としては、12.04は普通にはインストールできない(カーネルのバージョンの関係です。14.04は大丈夫です)のと、そのpcにはssdとhddが1つずつ入っていて、hddの方にWindowsが入っています。ssdの方を上書きするといいと思います。

**Comment by kimhc6028** [comment]
@furushchevさん
msiをもらったキムです。msiはこのまま使いたいですが、パスワードが掛かってます。もしよければ、(個人的にでも)pwを教えて下さいませんか

**Comment by furushchev** [comment]
パスワードは何の変哲もないので、研究室にいる人に聞いてもらえると解ると思います。
もし研究室以外にいる場合、僕がパスワードを適当なものに一時的に変えようと思います。
現在ノートパソコンはグローバルIPを持てるネットワークにつながっていますか？
もしつながっているなら、`hostname -I`をターミナルで実行して、結果を貼ってくれると嬉しいです。

**Comment by furushchev** [comment]
@wkentaro さんがパスワードを教えてくれたようです。
