### ISSUE TITLE
2015 11 04 の宿題

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2015-semi#9]
issueを３個ぐらい書いて下さい．できれば，このリポジトリ以外のところで．書いたら，ここに報告しておいて下さい．

**Comment by knorth55** [comment]
baxter_simulator:gripper_simulationのbaxter_sim_examplesのCMakeListとpackageをPRしました。
元々がcatkin buildできなかったのでおそらくあってるかと思いますが少し心配です。
[#61](https://github.com/RethinkRobotics/baxter_simulator/pull/61)

**Comment by kimhc6028** [comment]
turtlebot/turtlebot_armに7dofのアームがあるかを訪ねておきました。
jsk-eshu/robot-programmingに、資料の中でおかしいじと思われるところをどんどんissueしている中です。

**Comment by ban-masa** [comment]
https://github.com/ros-naoqi/nao_virtual にissueをとりあえず２つ書きました。
